#pragma once
#include "piece.h"

#define A_FILE 0
#define B_FILE 1
#define C_FILE 2
#define D_FILE 3
#define E_FILE 4
#define F_FILE 5
#define G_FILE 6
#define H_FILE 7

#define RANK_1 0
#define RANK_2 1
#define RANK_3 2
#define RANK_4 3
#define RANK_5 4
#define RANK_6 5
#define RANK_7 6
#define RANK_8 7

#define MAKE_CONSTANT_COORD(_file, _rank) ((struct coord) { .file = _file##_FILE, .rank = RANK_##_rank })

#define A1 MAKE_CONSTANT_COORD(A,1)
#define A2 MAKE_CONSTANT_COORD(A,2)
#define A3 MAKE_CONSTANT_COORD(A,3)
#define A4 MAKE_CONSTANT_COORD(A,4)
#define A5 MAKE_CONSTANT_COORD(A,5)
#define A6 MAKE_CONSTANT_COORD(A,6)
#define A7 MAKE_CONSTANT_COORD(A,7)
#define A8 MAKE_CONSTANT_COORD(A,8)

#define B1 MAKE_CONSTANT_COORD(B,1)
#define B2 MAKE_CONSTANT_COORD(B,2)
#define B3 MAKE_CONSTANT_COORD(B,3)
#define B4 MAKE_CONSTANT_COORD(B,4)
#define B5 MAKE_CONSTANT_COORD(B,5)
#define B6 MAKE_CONSTANT_COORD(B,6)
#define B7 MAKE_CONSTANT_COORD(B,7)
#define B8 MAKE_CONSTANT_COORD(B,8)

#define C1 MAKE_CONSTANT_COORD(C,1)
#define C2 MAKE_CONSTANT_COORD(C,2)
#define C3 MAKE_CONSTANT_COORD(C,3)
#define C4 MAKE_CONSTANT_COORD(C,4)
#define C5 MAKE_CONSTANT_COORD(C,5)
#define C6 MAKE_CONSTANT_COORD(C,6)
#define C7 MAKE_CONSTANT_COORD(C,7)
#define C8 MAKE_CONSTANT_COORD(C,8)

#define D1 MAKE_CONSTANT_COORD(D,1)
#define D2 MAKE_CONSTANT_COORD(D,2)
#define D3 MAKE_CONSTANT_COORD(D,3)
#define D4 MAKE_CONSTANT_COORD(D,4)
#define D5 MAKE_CONSTANT_COORD(D,5)
#define D6 MAKE_CONSTANT_COORD(D,6)
#define D7 MAKE_CONSTANT_COORD(D,7)
#define D8 MAKE_CONSTANT_COORD(D,8)

#define E1 MAKE_CONSTANT_COORD(E,1)
#define E2 MAKE_CONSTANT_COORD(E,2)
#define E3 MAKE_CONSTANT_COORD(E,3)
#define E4 MAKE_CONSTANT_COORD(E,4)
#define E5 MAKE_CONSTANT_COORD(E,5)
#define E6 MAKE_CONSTANT_COORD(E,6)
#define E7 MAKE_CONSTANT_COORD(E,7)
#define E8 MAKE_CONSTANT_COORD(E,8)

#define F1 MAKE_CONSTANT_COORD(F,1)
#define F2 MAKE_CONSTANT_COORD(F,2)
#define F3 MAKE_CONSTANT_COORD(F,3)
#define F4 MAKE_CONSTANT_COORD(F,4)
#define F5 MAKE_CONSTANT_COORD(F,5)
#define F6 MAKE_CONSTANT_COORD(F,6)
#define F7 MAKE_CONSTANT_COORD(F,7)
#define F8 MAKE_CONSTANT_COORD(F,8)

#define G1 MAKE_CONSTANT_COORD(G,1)
#define G2 MAKE_CONSTANT_COORD(G,2)
#define G3 MAKE_CONSTANT_COORD(G,3)
#define G4 MAKE_CONSTANT_COORD(G,4)
#define G5 MAKE_CONSTANT_COORD(G,5)
#define G6 MAKE_CONSTANT_COORD(G,6)
#define G7 MAKE_CONSTANT_COORD(G,7)
#define G8 MAKE_CONSTANT_COORD(G,8)

#define H1 MAKE_CONSTANT_COORD(H,1)
#define H2 MAKE_CONSTANT_COORD(H,2)
#define H3 MAKE_CONSTANT_COORD(H,3)
#define H4 MAKE_CONSTANT_COORD(H,4)
#define H5 MAKE_CONSTANT_COORD(H,5)
#define H6 MAKE_CONSTANT_COORD(H,6)
#define H7 MAKE_CONSTANT_COORD(H,7)
#define H8 MAKE_CONSTANT_COORD(H,8)
